version: "3.8"

services:
  frontend:
    build:
      context: ./frontend # Path to your frontend code
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend # Path to your backend code
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    environment:
      - NODE_ENV=production
      - GOOGLE_GEOCODE_API_KEY=${GOOGLE_GEOCODE_API_KEY}
      - NINJA_API_KEY=${NINJA_API_KEY}
      - CALORIERAPIDAPI_KEY=${CALORIERAPIDAPI_KEY}
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
