# Backend Dockerfile
FROM node:20.17.0-alpine

# Use production node environment by default
ENV NODE_ENV production

WORKDIR /usr/src/app

# Download dependencies
COPY package*.json ./
RUN npm ci --omit=dev

# Run as non-root user
USER node

# Copy application files
COPY --chown=node:node . .

# Expose port
EXPOSE 8000

# Start application
CMD ["npm", "start"]